language: cpp
compiler: gcc
dist: focal
before_install:
  - sudo apt-get install python-is-python3
  - sudo apt-get install python3-pip
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - python --version

after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
- echo 'update version according to the tag name'
- sed -i "/version=/d" setup.py
- sed -i 's|long_description=readme(),|long_description=readme(),\n      version='"'${TRAVIS_TAG}'"',|'
  setup.py
- cat setup.py | grep version
deploy:
  provider: pypi
  user: __token__
  password: err
  skip_cleanup: true
  on:
    branch: test_travis
